services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hurz
      POSTGRES_USER: hurz
      POSTGRES_PASSWORD: hurz
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://hurz:hurz@db/hurz
    ports:
      - "5000:5000"
    depends_on:
      - db
